//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg
    {
        public System.Guid id { get; set; }
        public string textMsg { get; set; }
        public System.DateTime msgDate { get; set; }
        public System.Guid userId { get; set; }
        public Nullable<System.Guid> toId { get; set; }
    
        public virtual user user { get; set; }
    }
}
