//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpleChat
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.msgs = new HashSet<msg>();
        }
    
        public System.Guid id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<msg> msgs { get; set; }
    }
}
